In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

Transposition d’une matrice

In [11]:
arr.T

array([[ 1,  6,  1],
       [ 2,  7,  2],
       [ 3,  8,  3],
       [ 4,  9,  4],
       [ 5, 10,  5]])

matrice identité: une matrice carrée ne contenant que des 0 et des 1 sur la diagonale HG>BD

In [12]:
ident = np.identity(5)
ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

une matrice inverse de A, c’est la matrice B dont le produit matriciel np.dot(A,B) donne la matrice identité.

In [22]:
x = np.array([1,2,3,4,5])
A = np.array([x,5+x,10+x,15+x,20+x])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
randmat = np.random.rand(5,5)
print(randmat)
B = np.linalg.inv(randmat)
print(B)
ident_presque = np.dot(randmat, B)
print(np.round(ident_presque))

[[0.26015435 0.09849758 0.7939898  0.27379494 0.55053139]
 [0.65678512 0.81980636 0.26078845 0.8265733  0.90339899]
 [0.91767626 0.49983347 0.58223256 0.83450629 0.26895693]
 [0.70068171 0.87416841 0.67911659 0.76040273 0.61557085]
 [0.63071499 0.62160246 0.03529804 0.78177339 0.11805706]]
[[-3.8907413   1.54918235  4.70748128  0.2038561  -5.49863047]
 [-1.64700977 -0.63188594 -0.79004115  2.88278809 -0.71573509]
 [ 1.269819   -1.365165   -0.62003857  1.00838319  0.67972086]
 [ 4.40188845 -0.96186096 -3.20269061 -2.36793828  6.47641131]
 [-0.07087402  1.82821995  0.40384653 -0.88877428 -1.47477381]]
[[ 1. -0. -0.  0.  0.]
 [ 0.  1. -0. -0.  0.]
 [-0. -0.  1.  0. -0.]
 [-0.  0.  0.  1.  0.]
 [-0.  0. -0. -0.  1.]]
