# FONCTIONS NUMPY

In [2]:
import numpy as np

### ARANGE
crée un array numpy
prend les mêmes paramètres que range() de pyrhon, mais accepte des *step* non entiers, comme .2


In [9]:
liste = np.arange(0,8,.2)
liste

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8])

### RANDOM
Une classe qui possède de nombreuses méthodes afin de générer des nombres aléatoires.

#### random.randint :
- Comme son nom l’indique, génère un entier aléatoire entre deux balises.
- Les deux premiers paramètres sont les classiques *start* et *stop*.
- La troisième paramètre permet de générer un tableau de résulats sous forme d’array numpy.
- Si le prosième paramètre est un tuple, il précise les dimensions de cet array.


In [15]:
ints = np.random.randint(1,11,(3,3))
ints

array([[9, 7, 6],
       [1, 6, 3],
       [4, 6, 2]])

#### random.randn :
- Cette fonction génère une série de nombres aléatoires selon une répartition gaussienne, en anglais « standard normal distribution ».
- Prend en paramètre un tuple de dimensions : par exemple, (40,10) donnera 40 éléments composés chacun de 10 éléménts

In [18]:
signal = np.random.randn(40,10)

fonctions = {
    "maximum" : np.max, 
    "minimum" : np.min, 
    "médiane" : np.median, 
    "moyenne" : np.mean, 
    "écart-type" : np.std
    }

def launch_functions(arr):
    print("–––")
    for name, function in fonctions.items() :
        print(name, ":", function(arr))

launch_functions(signal)

–––
maximum : 3.3033842243367335
minimum : -2.494741305805717
médiane : -0.007138787847978835
moyenne : -0.0037135648595537397
écart-type : 0.9454091583707992


#### LINSPACE
- Crée un array entre les valeurs *start* et *stop*.
- Le troisième paramètre définit le nombre d’éléménts à créer.
- Le paramètre *stop* ne fonctionne pas comme d’habitude et inclus la valeur.

In [23]:
liste_espacee = np.linspace(1,8,15)

liste_espacee

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. ])

In [29]:
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
x = np.asarray([f for f in range(10)])
indice = x>5
print(indice)
x[indice] = 10 
print(x)
x[indice] = 20 
print(x)


[False False False False False False  True  True  True  True]
[ 0  1  2  3  4  5 10 10 10 10]
[ 0  1  2  3  4  5 20 20 20 20]


solutions pour remplacer les elements d’une liste par 0 ou 1 en fonction d’une condition : 

In [63]:
li = np.array([f for f in range(11)])

li = li > 5
li = li + 4
li = li * 5

li

array([20, 20, 20, 20, 20, 20, 25, 25, 25, 25, 25])

In [64]:
li = [0,1,0,1,0,1]

res = []
for i, x in enumerate(li) :
    if x : res.append(i)

res

[1, 3, 5]